# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Edge Medical Writing
email: hfosam@theedgemedicalwriting.com
description: Giving you the Edge
url: https://sfosam12.github.io/theedge/
baseurl: /theedge


# Build settings
markdown: kramdown
